FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY prisma/ ./prisma/
COPY backend/ ./backend/

RUN npm install
RUN npx prisma generate

EXPOSE 3001
CMD ["npm", "run", "start", "--workspace=backend"]
